version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb
    restart: always

  api:
    image: marketplace-squid
    build: .
    environment:
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
      - GQL_PORT=4350
    ports:
      # GraphQL endpoint at port 4350
      - "127.0.0.1:4350:4350"
    command: ["sqd", "serve:prod"]
    depends_on:
      - db
    restart: always

  processor:
    image: marketplace-squid
    build: .
    environment:
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASS=postgres
    ports:
      # prometheus metrics exposed at port 3000
      - "127.0.0.1:3000:3000"
    command: ["sqd", "process:prod"]
    depends_on:
      - db
    restart: always
